// src/app/blog/page.tsx
'use client'

import { useState, useEffect, useCallback, Suspense } from 'react'
import { motion } from 'framer-motion'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { Search, Calendar, Tag, ArrowRight, Edit, Trash2, Loader2 } from 'lucide-react'
import { useAdmin } from '@/hooks/use-admin'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'

interface Post {
  id: number
  title: string
  excerpt: string | null
  slug: string
  pinned: boolean
  views: number
  createdAt: string
  category: { name: string; slug: string } | null
  tags: { id: number; name: string; slug: string }[]
  _count: { comments: number; likes: number }
}

interface Category {
  id: number
  name: string
  slug: string
  _count: { posts: number }
}

interface PostsResponse {
  posts: Post[]
  total: number
  page: number
  totalPages: number
}

const POSTS_PER_PAGE = 9

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.1 },
  },
}

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5 },
  },
}

function BlogContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { isAdmin } = useAdmin()

  const [posts, setPosts] = useState<Post[]>([])
  const [categories, setCategories] = useState<Category[]>([])
  const [totalPages, setTotalPages] = useState(1)
  const [total, setTotal] = useState(0)
  const [isLoading, setIsLoading] = useState(true)
  const [deletingId, setDeletingId] = useState<number | null>(null)

  const page = parseInt(searchParams.get('page') || '1')
  const activeCategory = searchParams.get('category') || ''
  const activeTag = searchParams.get('tag') || ''
  const [searchQuery, setSearchQuery] = useState(searchParams.get('search') || '')

  const loadCategories = useCallback(async () => {
    try {
      const res = await fetch('/api/categories')
      const data = await res.json()
      if (Array.isArray(data)) setCategories(data)
    } catch (e) {
      console.error('Failed to load categories:', e)
    }
  }, [])

  const loadPosts = useCallback(async () => {
    setIsLoading(true)
    try {
      const params = new URLSearchParams()
      params.set('page', String(page))
      params.set('limit', String(POSTS_PER_PAGE))
      if (activeCategory) params.set('category', activeCategory)
      if (activeTag) params.set('tag', activeTag)
      if (searchQuery) params.set('search', searchQuery)

      const res = await fetch(`/api/posts?${params.toString()}`)
      const data: PostsResponse = await res.json()
      setPosts(data.posts || [])
      setTotal(data.total || 0)
      setTotalPages(data.totalPages || 1)
    } catch (e) {
      console.error('Failed to load posts:', e)
    } finally {
      setIsLoading(false)
    }
  }, [page, activeCategory, activeTag, searchQuery])

  useEffect(() => {
    loadCategories()
  }, [loadCategories])

  useEffect(() => {
    loadPosts()
  }, [loadPosts])

  const updateUrl = (updates: Record<string, string>) => {
    const params = new URLSearchParams(searchParams)
    Object.entries(updates).forEach(([key, value]) => {
      if (value) params.set(key, value)
      else params.delete(key)
    })
    router.push(`?${params.toString()}`)
  }

  const handleCategoryChange = (slug: string) => {
    updateUrl({ category: slug || '', tag: '', page: '1' })
  }

  const handleSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQuery(e.target.value)
  }

  useEffect(() => {
    const timer = setTimeout(() => {
      if (searchQuery !== searchParams.get('search')) {
        updateUrl({ search: searchQuery, page: '1' })
      }
    }, 400)
    return () => clearTimeout(timer)
  }, [searchQuery])

  const handlePageChange = (newPage: number) => {
    updateUrl({ page: String(newPage) })
  }

  const handleDelete = async (id: number, title: string) => {
    if (!confirm(`确定要删除「${title}」吗？`)) return
    setDeletingId(id)
    try {
      await fetch('/api/blog', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'delete', id, password: 'admin123' }),
      })
      await loadPosts()
    } catch (e) {
      console.error('Failed to delete:', e)
    } finally {
      setDeletingId(null)
    }
  }

  const formatDate = (date: string) => {
    return new Date(date).toLocaleDateString('zh-CN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })
  }

  return (
    <div className="pt-24 pb-20 px-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="max-w-7xl mx-auto"
      >
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">技术博客</h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            分享技术见解、学习心得和开发经验
          </p>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="mb-8"
        >
          <div className="relative max-w-md mx-auto">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <Input
              value={searchQuery}
              onChange={handleSearch}
              placeholder="搜索文章..."
              className="pl-10"
            />
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="flex flex-wrap justify-center gap-2 mb-10"
        >
          <button
            onClick={() => handleCategoryChange('')}
            className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
              !activeCategory && !activeTag
                ? 'bg-primary text-primary-foreground'
                : 'bg-accent text-muted-foreground hover:bg-primary/10'
            }`}
          >
            全部 ({total})
          </button>
          {categories.map((cat) => (
            <button
              key={cat.id}
              onClick={() => handleCategoryChange(cat.slug)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
                activeCategory === cat.slug
                  ? 'bg-primary text-primary-foreground'
                  : 'bg-accent text-muted-foreground hover:bg-primary/10'
              }`}
            >
              {cat.name} ({cat._count.posts})
            </button>
          ))}
        </motion.div>

        {isLoading ? (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[1, 2, 3, 4, 5, 6].map((i) => (
              <div key={i} className="animate-pulse bg-card rounded-xl p-6">
                <div className="h-40 bg-muted rounded-2xl mb-4" />
                <div className="h-4 bg-muted rounded w-3/4 mb-2" />
                <div className="h-4 bg-muted rounded w-1/2" />
              </div>
            ))}
          </div>
        ) : posts.length === 0 ? (
          <div className="text-center py-20">
            <div className="text-6xl mb-4">📝</div>
            <p className="text-muted-foreground text-lg">暂无文章</p>
          </div>
        ) : (
          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-100px' }}
            className="grid md:grid-cols-2 lg:grid-cols-3 gap-8"
          >
            {posts.map((post, index) => (
              <motion.article
                key={post.id}
                variants={itemVariants}
                whileHover={{ scale: 1.02 }}
                className="group bg-card rounded-xl overflow-hidden shadow-sm hover:shadow-lg transition-shadow card-hover"
              >
                <Link href={`/blog/${post.slug}`}>
                  <div className="relative h-48 bg-gradient-to-br from-primary/20 to-accent/20 flex items-center justify-center">
                    {post.pinned && (
                      <span className="absolute top-3 left-3 z-10 px-2.5 py-1 text-xs rounded-full bg-primary text-primary-foreground">
                        置顶
                      </span>
                    )}
                    <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity" />
                    <div className="text-4xl">📝</div>
                  </div>
                </Link>
                <div className="p-6">
                  <div className="flex flex-wrap gap-2 mb-3">
                    {post.category && (
                      <span className="px-2.5 py-1 text-xs rounded-full bg-primary/10 text-primary">
                        {post.category.name}
                      </span>
                    )}
                    {post.tags.map((tag) => (
                      <span key={tag.id} className="px-2.5 py-1 text-xs rounded-full bg-accent text-muted-foreground">
                        <Tag className="w-3 h-3 inline mr-1" />
                        {tag.name}
                      </span>
                    ))}
                  </div>
                  <Link href={`/blog/${post.slug}`}>
                    <h2 className="text-xl font-bold mb-2 group-hover:text-primary transition-colors line-clamp-2">
                      {post.title}
                    </h2>
                  </Link>
                  {post.excerpt && (
                    <p className="text-sm text-muted-foreground line-clamp-2 mb-3">{post.excerpt}</p>
                  )}
                  <div className="flex items-center gap-3 text-xs text-muted-foreground">
                    <Calendar className="w-3 h-3" />
                    <span>{formatDate(post.createdAt)}</span>
                    <span>· {post._count.comments} 评论</span>
                    <span>· {post._count.likes} 赞</span>
                  </div>
                  {isAdmin && (
                    <div className="flex gap-2 mt-3 pt-3 border-t border-border">
                      <Link href={`/blog/${post.slug}?edit=1`}>
                        <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-primary">
                          <Edit className="w-4 h-4 mr-1" /> 编辑
                        </Button>
                      </Link>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleDelete(post.id, post.title)}
                        disabled={deletingId === post.id}
                        className="text-muted-foreground hover:text-destructive"
                      >
                        {deletingId === post.id ? (
                          <Loader2 className="w-4 h-4 mr-1 animate-spin" />
                        ) : (
                          <Trash2 className="w-4 h-4 mr-1" />
                        )}
                        删除
                      </Button>
                    </div>
                  )}
                </div>
              </motion.article>
            ))}
          </motion.div>
        )}

        {totalPages > 1 && (
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="mt-12 flex items-center justify-center gap-2"
          >
            <Button
              variant="outline"
              size="sm"
              disabled={page <= 1}
              onClick={() => handlePageChange(page - 1)}
            >
              ← 上一页
            </Button>
            <span className="px-4 py-2 text-sm text-muted-foreground">
              {page} / {totalPages}
            </span>
            <Button
              variant="outline"
              size="sm"
              disabled={page >= totalPages}
              onClick={() => handlePageChange(page + 1)}
            >
              下一页 →
            </Button>
          </motion.div>
        )}
      </motion.div>
    </div>
  )
}

function BlogFallback() {
  return (
    <div className="pt-24 pb-20 px-4">
      <div className="max-w-7xl mx-auto text-center">
        <div className="animate-pulse space-y-4">
          <div className="h-8 bg-muted rounded w-1/3 mx-auto mb-12" />
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {[1, 2, 3, 4, 5, 6].map((i) => (
              <div key={i} className="h-64 bg-muted rounded-xl" />
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

export default function BlogPage() {
  return (
    <Suspense fallback={<BlogFallback />}>
      <BlogContent />
    </Suspense>
  )
}

// blog-site/pages/blog/index.vue
<template>
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
    <h1 class="text-4xl font-bold mb-8 animate-slide-up">博客文章</h1>

    <!-- Search Bar -->
    <div class="relative mb-8 animate-slide-up" style="animation-delay: 0.05s">
      <input
        v-model="searchQuery"
        type="text"
        placeholder="搜索文章..."
        class="w-full px-4 py-3 pl-12 rounded-xl border border-[rgb(var(--color-border))] bg-[rgb(var(--color-bg))] focus:outline-none focus:ring-2 focus:ring-[rgb(var(--color-accent))]/50 focus:border-transparent transition-all"
        @input="debouncedSearch"
      />
      <svg class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-[rgb(var(--color-text-secondary))]" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
    </div>

    <!-- Category & Tag Filters -->
    <div class="flex flex-wrap gap-2 mb-8 animate-slide-up" style="animation-delay: 0.1s">
      <button
        :class="[
          'px-4 py-2 rounded-full text-sm font-medium transition-all',
          activeCategory === null
            ? 'bg-[rgb(var(--color-accent))] text-white'
            : 'bg-[rgb(var(--color-bg-secondary))] text-[rgb(var(--color-text-secondary))] hover:bg-[rgb(var(--color-accent))]/10'
        ]"
        @click="activeCategory = null; loadPosts()"
      >
        全部
      </button>
      <button
        v-for="cat in categories"
        :key="cat.id"
        :class="[
          'px-4 py-2 rounded-full text-sm font-medium transition-all',
          activeCategory === cat.slug
            ? 'bg-[rgb(var(--color-accent))] text-white'
            : 'bg-[rgb(var(--color-bg-secondary))] text-[rgb(var(--color-text-secondary))] hover:bg-[rgb(var(--color-accent))]/10'
        ]"
        @click="activeCategory = cat.slug; loadPosts()"
      >
        {{ cat.name }} ({{ cat._count.posts }})
      </button>
    </div>

    <!-- Posts Grid -->
    <div v-if="pending" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
      <div v-for="i in 6" :key="i" class="animate-pulse">
        <div class="h-40 bg-[rgb(var(--color-bg-secondary))] rounded-2xl mb-4" />
        <div class="h-4 bg-[rgb(var(--color-bg-secondary))] rounded w-3/4 mb-2" />
        <div class="h-4 bg-[rgb(var(--color-bg-secondary))] rounded w-1/2" />
      </div>
    </div>

    <div v-else-if="!postsData?.posts?.length" class="text-center py-24">
      <p class="text-[rgb(var(--color-text-secondary))]">暂无文章</p>
    </div>

    <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
      <article
        v-for="(post, index) in postsData.posts"
        :key="post.id"
        class="group cursor-pointer animate-slide-up"
        :style="{ animationDelay: `${index * 0.05}s` }"
        @click="navigateTo(`/blog/${post.slug}`)"
      >
        <div class="relative overflow-hidden rounded-2xl mb-4 bg-[rgb(var(--color-bg-secondary))] aspect-[16/10]">
          <div v-if="post.pinned" class="absolute top-3 left-3 z-10 px-2.5 py-1 text-xs rounded-full bg-[rgb(var(--color-accent))] text-white">
            置顶
          </div>
          <div class="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
          <div class="absolute inset-0 flex items-center justify-center text-4xl">
            📝
          </div>
        </div>
        <div class="flex flex-wrap gap-2 mb-3">
          <span
            v-if="post.category"
            class="px-2.5 py-1 text-xs rounded-full bg-[rgb(var(--color-accent))]/10 text-[rgb(var(--color-accent))]"
          >
            {{ post.category.name }}
          </span>
          <span
            v-for="tag in post.tags"
            :key="tag.id"
            class="px-2.5 py-1 text-xs rounded-full bg-[rgb(var(--color-bg-secondary))] text-[rgb(var(--color-text-secondary))]"
          >
            {{ tag.name }}
          </span>
        </div>
        <h2 class="text-lg font-semibold mb-2 group-hover:text-[rgb(var(--color-accent))] transition-colors line-clamp-2">
          {{ post.title }}
        </h2>
        <p v-if="post.excerpt" class="text-sm text-[rgb(var(--color-text-secondary))] line-clamp-2 mb-3">
          {{ post.excerpt }}
        </p>
        <div class="flex items-center gap-4 text-xs text-[rgb(var(--color-text-secondary))]">
          <span>{{ formatDate(post.createdAt) }}</span>
          <span>· {{ post._count.comments }} 评论</span>
          <span>· {{ post._count.likes }} 赞</span>
        </div>
        <div v-if="isAdmin" class="flex gap-2 mt-3" @click.stop>
          <button
            @click="navigateTo(`/blog/${post.slug}?edit=1`)"
            class="px-3 py-1 text-xs rounded-lg border border-[rgb(var(--color-border))] hover:bg-[rgb(var(--color-accent))]/10 hover:border-[rgb(var(--color-accent))]/30 transition-all"
          >
            编辑
          </button>
          <button
            @click="deletePost(post.id, post.title)"
            class="px-3 py-1 text-xs rounded-lg border border-red-500/30 text-red-500 hover:bg-red-500/10 transition-all"
          >
            删除
          </button>
        </div>
      </article>
    </div>

    <!-- Pagination -->
    <div v-if="postsData && postsData.totalPages > 1" class="flex items-center justify-center gap-2 mt-16 animate-fade-in">
      <button
        :disabled="currentPage <= 1"
        class="px-4 py-2 rounded-lg border border-[rgb(var(--color-border))] disabled:opacity-50 hover:bg-[rgb(var(--color-bg-secondary))] transition-colors text-sm"
        @click="currentPage--; loadPosts()"
      >
        上一页
      </button>
      <span class="px-4 py-2 text-sm text-[rgb(var(--color-text-secondary))]">
        {{ currentPage }} / {{ postsData.totalPages }}
      </span>
      <button
        :disabled="currentPage >= postsData.totalPages"
        class="px-4 py-2 rounded-lg border border-[rgb(var(--color-border))] disabled:opacity-50 hover:bg-[rgb(var(--color-bg-secondary))] transition-colors text-sm"
        @click="currentPage++; loadPosts()"
      >
        下一页
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
const { isAdmin } = useAdmin()
const currentPage = ref(1)
const activeCategory = ref<string | null>(null)
const searchQuery = ref('')

interface Post {
  id: number
  title: string
  excerpt: string | null
  slug: string
  pinned: boolean
  createdAt: string
  category: { name: string; slug: string } | null
  tags: { id: number; name: string; slug: string }[]
  _count: { comments: number; likes: number }
}

interface Category {
  id: number
  name: string
  slug: string
  _count: { posts: number }
}

interface PostsResponse {
  posts: Post[]
  total: number
  page: number
  totalPages: number
}

const { data: categories } = await useFetch<Category[]>('/api/categories')
const { data: postsData, pending, refresh } = await useLazyFetch<PostsResponse>('/api/posts', {
  query: { page: currentPage, limit: 9 },
  watch: [currentPage],
})

async function loadPosts() {
  await refresh()
}

async function deletePost(id: number, title: string) {
  if (!confirm(`确定要删除「${title}」吗？`)) return
  try {
    await $fetch('/api/blog/delete', {
      method: 'POST',
      body: { id, password: 'admin123' },
    })
    await refresh()
  } catch (e: any) {
    alert(e.message || '删除失败')
  }
}

let debounceTimer: NodeJS.Timeout
function debouncedSearch() {
  clearTimeout(debounceTimer)
  debounceTimer = setTimeout(async () => {
    currentPage.value = 1
    await refresh()
  }, 300)
}

function formatDate(date: string) {
  return new Date(date).toLocaleDateString('zh-CN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}
</script>
